#! /bin/sh

sxhkd &
compton --backend glx -b -cz -t-4 -l-3 -r4 -o0.55 --blur-background --blur-method kawase --blur-strength 12 --vsync opengl --config /dev/null &
#compton --config ~/.config/compton/compton.conf &
feh --bg-fill ~/Downloads/background.jpg &
polybar -r -q main &
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          20
bspc config top_padding		45
bspc config bottom_padding 	10
bspc config left_padding	10
bspc config right_padding	10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

